checker_dir: sanity/checkers
file_rules:
  ^.*$:
    - "^file_.*$"
directory_rules:
  - "^dir_.*$"
parameters:
  file_namechecker:
    filename_pattern: "^.*-asset-.*$"
  file_sizechecker:
    min_size: 1
  dir_filecountchecker:
    max_file_count: 3
  dir_hasfilechecker:
    files_list:
      - "test.t"
      - "test.png"
recursive: true