checker_dir: sanity/checkers
file_checker_associations:
  ^.*\.txt$:
    - "^file_.*$"
directory_checks:
  - "^dir_.*$"
parameters:
  file_namechecker:
    filename_pattern: "^.*-asset-.*$"
  dir_filecountchecker:
    max_file_count: 3
recursive: true